Resources:
  myEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0f34c5ae932e6f0e4"
      InstanceType: t2.micro
      KeyName: my-keypair
      SecurityGroupIds:
        - "sg-0f124803c76014a13"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum update -y
            yum install nginx -y
            systemctl start nginx
            systemctl status 
            echo "<html><center><h1> Hello my web page! </h></center></html>" > /usr/share/nginx/html/hello.html 